apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy
  labels:
    run: deploy-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod-1
  template:
    metadata:
      name: podpython
      labels:
        app: pod-1
    spec:
      containers:
        - name: alura
          image: marcossales47/alura-challenge:latest
          ports:
          - containerPort: 8000

---

apiVersion: v1
kind: Service
metadata:
  name: nodeportalura
  labels:
    service: pod-alura
spec:
  type: NodePort
  selector:
    app: pod-1
  ports:
  - port: 7070
    targetPort: 8000
    nodePort: 31750
